apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd
spec:
  channel: alpha
  installPlanApproval: Automatic
  # Must be called argocd-operator otherwise it fails to install
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
