kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-cluster-admin
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccount:argocd:argocd-application-controller
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccount:argocd:argocd-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
